---
- name: register app on k8s with consul
  hosts: all
  become: true

  tasks:
   - name: register jenkins service with curl check
     consul:
       service_name: myapp
       service_port: 31616
       script: curl http://localhost:31616
       interval: 10s