---
- name: register prometheus service with consul
  hosts: all
  become: true

  tasks:
   - name: register prometheus service with curl check
     consul:
       service_name: grafana
       service_port: 3000
       script: curl http://localhost:9090
       interval: 3s