---
- name: register jenkins service with consul
  hosts: all
  become: true

  tasks:
   - name: register jenkins service with curl check
     consul:
       service_name: jenkins
       service_port: 8080
       script: curl http://localhost:8080
       interval: 10s