---
- name: Install node exporter
  hosts: all
  become: true

  tasks:
   - name: General | Load varibles
     include_vars:
        file: vars.yml

   - name: create group node_exporter
     group:
       name: node_exporter
       state: present

   - name: create user node_exporter in group node_exporter
     user:
       name: node_exporter
       group: node_exporter

   - name: Install node-exporter
     become: true
     unarchive:
       src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
       remote_src: yes
       dest: /tmp/
       creates: /tmp/prometheus

   - name: Copy  node_exporter binary to /usr/local/bin/
     become: true
     copy:
       src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
       dest: "/usr/local/bin/"
       owner: node_exporter
       mode: 0555

   - name: configure service node_exporter
     become: true
     copy:
       src: node_exporter.service
       dest: /etc/systemd/system/

   - name: start/restart service node_exporter
     systemd:
        name: node_exporter
        state: started
        daemon_reload: yes
        enabled: yes

