---
- name: Install prometheus and node exporter
  hosts: all
  become: true

  tasks:
   - name: General | Load varibles
     include_vars:
        file: vars.yml


   - name: create group prometheus
     group:
       name: prometheus
       state: present

   - name: create user prometheus in group prometheus
     user:
       name: prometheus
       group: prometheus

   - name: create group node_exporter
     group:
       name: node_exporter
       state: present

   - name: create user node_exporter in group node_exporter
     user:
       name: node_exporter
       group: node_exporter

   - name: create prometheus config directory
     become: true
     file:
       path: /etc/prometheus
       state: directory
       group: prometheus
       owner: prometheus

   - name: create prometheus data directory
     become: true
     file:
       path: /var/lib/prometheus
       state: directory
       group: prometheus
       owner: prometheus

   - name: Install prometheus
     become: true
     unarchive:
       src: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
       remote_src: yes
       dest: /tmp/
       creates: /tmp/prometheus

   - name: Install node-exporter
     become: true
     unarchive:
       src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
       remote_src: yes
       dest: /tmp/
       creates: /tmp/prometheus

   - name: Copy  prometheus binary to /usr/local/bin/
     become: true
     copy:
       src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus"
       dest: "/usr/local/bin/"
       owner: prometheus
       mode: 0555

   - name: Copy  prometheus binary to /usr/local/bin/
     become: true
     copy:
       src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/promtool"
       dest: "/usr/local/bin/"
       owner: prometheus
       mode: 0555

   - name: Copy  node_exporter binary to /usr/local/bin/
     become: true
     copy:
       src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
       dest: "/usr/local/bin/"
       owner: node_exporter
       mode: 0555

   - name: Copy  consoles to /etc/prometheus
     become: true
     copy:
       src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/consoles"
       dest: /etc/prometheus
       owner: prometheus

   - name: Copy  console_libraries  to /etc/prometheus
     become: true
     copy:
       src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/console_libraries"
       dest: /etc/prometheus
       owner: prometheus

   - name: configure prometheus with targets
     become: true
     copy:
       src: prometheus.yml
       dest: /etc/prometheus/

   - name: configure service prometheus
     become: true
     copy:
       src: prometheus.service
       dest: /etc/systemd/system/

   - name: start/restart service prometheus
     systemd:
        name: prometheus
        state: started
        daemon_reload: yes
        enabled: yes

   - name: configure service node_exporter
     become: true
     copy:
       src: node_exporter.service
       dest: /etc/systemd/system/

   - name: start/restart service node_exporter
     systemd:
        name: node_exporter
        state: started
        daemon_reload: yes
        enabled: yes

