### The following is the "svc.yml" file used in the module
apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  labels:
    app: hello-world
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    nodePort: 31616
    protocol: TCP
  selector:
    app: hello-world
