apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-rc
spec:
  replicas: 5
  selector:
    app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-ctr
        image: polonskyirena/app_py:v0
        ports:
        - containerPort: 5000
ubuntu@ip-10-0-1-76:~$ cat svc.yml
### The following is the "svc.yml" file used in the module
apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  labels:
    app: hello-world
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 31616
    protocol: TCP
  selector:
    app: hello-world
